### ISSUE TITLE
os.getlogin does not work

### ISSUE THREAD

**Issue by ghost** [parmentelat/apssh#1]
apssh does not work because of an exception raised by os.getlogin():

```
$ apssh
Traceback (most recent call last):
  File "/home/asher256/.local/bin/apssh", line 3, in <module>
    from apssh.apssh import Apssh
  File "/home/asher256/.local/lib/python3.5/site-packages/apssh/apssh.py", line 13, in <module>
    from .config import default_time_name, default_timeout, default_username, default_private_key, default_remote_workdir
  File "/home/asher256/.local/lib/python3.5/site-packages/apssh/config.py", line 5, in <module>
    default_username =              os.getlogin()
FileNotFoundError: [Errno 2] No such file or directory
```

According to http://stackoverflow.com/questions/4399617/python-os-getlogin-problem :

```
From the os.getlogin() docs: "Returns the user logged in to the controlling terminal of the process." Your script does not have a controlling terminal when run from cron. The docs go on to suggest: "For most purposes, it is more useful to use the environment variable LOGNAME to find out who the user is, or pwd.getpwuid(os.getuid())[0] to get the login name of the currently effective user id."
```

I suggest you to replace os.getlogin with:

```
import pwd
import os

getlogin = lambda: pwd.getpwuid(os.getuid())[0]
default_username = getlogin()
```

I my case, it solved the issue.

**Comment by parmentelat** [comment]
sounds good to me, will do that when I have a chance

**Comment by ghost** [comment]
AttributeError: 'module' object has no attribute 'getlogin'

**Comment by parmentelat** [comment]
Hi
can you please elaborate a little on this issue ?

* what version of apssh are you using ?
* on what operating system is that ?
* what is exactly the command line sentence that triggered that message ?

I could find only one instance of a call to that method, and it's protected in a try/except so this case should be taken care of

---
the only place where we need to call this is in order to get a decent default for the username to use when logging into a remote box

os.getlogin() has its caveats - as pointed out by @Asher256 - and using `getpass.getuser()`, as the Python doc now suggests, is probably the way to go

anybody up for a PR ?
